checklist/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('mylist.urls', namespace='mylist')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('userena.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            url(r'', include('django.contrib.staticfiles.urls')),
    )

mylist/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required as LR, permission_required
from mylist.views import HomeIndex, PublicView, DetailView, AddNewView, UpdateTaskView, UpdateChecklist, \
    CloneChecklistView, LateTaskView, AddTaskView

urlpatterns = patterns('mylist.views',
    url('^$', LR(HomeIndex.as_view()), name='index'),
    url('^public/$', PublicView.as_view(), name='public'),
    url('^add/$', LR(AddNewView.as_view()), name='add'),
    url('^ajax/task/(?P<id>\d+)/update/$', permission_required('tasks.can_edit')(UpdateTaskView.as_view()), name='update_task'),

    url('^ajax/checklist/(?P<id>\d+)/clone/$', LR(CloneChecklistView.as_view()), name='clone_checklist'),
    url('^checklist/(?P<slug>[-_\w]+)/(?P<id>\d+)/$', DetailView.as_view(), name='detail'),
    url('^checklist/(?P<id>\d+)/update/$', UpdateChecklist.as_view(), name='update'),
    url('^tasks/late/$', LR(LateTaskView.as_view()), name='late_tasks'),
    url('^tasks/add/$', LR(AddTaskView.as_view()), name='add_tasks'),
)

userena/urls.py
from django.conf.urls import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

mylist/models.py
import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from userena.utils import user_model_label
from django.utils.timezone import utc

class CheckList(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    slug = models.CharField(_('Slug'), max_length=255)

    rate = models.FloatField(_('Rate'), null=True, blank=True)
    owner = models.ForeignKey(user_model_label, null=True, related_name='owner', verbose_name=_('Owner'))
    start_at = models.DateTimeField(_('Start at'))

    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', verbose_name=_('Parent'), on_delete=models.SET_NULL)
    is_deleted = models.BooleanField(_('Deleted'), default=False)
    created_at = models.DateTimeField(_('Created at'), null=True, auto_now_add=True)
    public = models.BooleanField(_('Public'), default=False,
                                 help_text=_('Check this if you want to publish checklist.'))

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)

        #calculate due date for tasks
        for task in self.tasks.filter(is_deleted = False):
            task.calculate_real_due_date()
            task.save()

        super(CheckList, self).save(*args, **kwargs)

    def get_list_task(self):
        return self.tasks.filter(is_deleted=False, parent__isnull=True)

    def count_task(self):
        return self.tasks.filter(is_deleted=False).count()

    def get_absolute_url(self):
        return reverse('mylist:detail', kwargs={'slug': self.slug, 'id': self.id})

    class Meta:
        ordering = ('-created_at',)


class Task(models.Model):
    title = models.CharField(_('Title'), max_length=255)
    check_list = models.ForeignKey(CheckList, related_name='tasks', verbose_name=_('Checklist'))
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', verbose_name=_('Parent'))

    due_date = models.PositiveSmallIntegerField(_('Due date'), default=0)
    real_due_date = models.DateTimeField( null= True, blank= True)

    is_checked = models.BooleanField(_('Checked'), default=False)
    is_deleted = models.BooleanField(_('Deleted'), default=False)

    order = models.PositiveSmallIntegerField(_('Order'), default=0)
    last_reminder = models.DateTimeField( null= True, blank= True )


    def save(self, *args, **kwargs):
        #calculate due date for tasks
        self.calculate_real_due_date()

        super(Task, self).save(*args, **kwargs)

    def calculate_real_due_date(self):


        if self.parent_id > 0:
            self.due_date = self.parent.due_date

        if self.due_date is None:
            self.due_date = 0

        if self.check_list.start_at:
            self.real_due_date = self.check_list.start_at + datetime.timedelta(days=int(self.due_date))
            #self.save()

    def can_edit(self, user):

        if self.check_list.owner == user or user.is_staff:
            return True

        return False

    def __unicode__(self):
        return self.title

    def get_by_is_checked(self):
        return self.objects.filter(is_checked=True, is_deleted=False)

    def get_child_task(self):
        return self.children.filter(is_deleted=False)

    def count_child_task(self):
        return self.get_child_task().count()

    def is_overdated(self):
        if self.check_list.start_at and self.due_date > 0:
            if (self.check_list.start_at + datetime.timedelta(days=self.due_date)) < timezone.now():
                return True
        return False

    def remain_date(self):
        if not self.is_overdated():
            now = datetime.datetime.utcnow().replace(tzinfo=utc)
            return (self.check_list.start_at + datetime.timedelta(days=self.due_date)) - now
        return None

    class Meta:
        ordering = ('-check_list', 'order',)

mylist/views.py
import datetime
from django.core.urlresolvers import reverse

from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.views.generic import ListView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
import simplejson

from mylist.models import CheckList, Task
from mylist.forms import ChecklistForm


class HomeIndex(ListView):
    template_name = "mylist/home.html"
    context_object_name = 'items'
    active = ''
    queryset = CheckList.objects.filter(is_deleted=False)

    def get(self, request, *args, **kwargs):
        order = request.GET.get('order', None)
        if order == 'recent':
            self.queryset = CheckList.objects.filter(is_deleted=False, owner=request.user)
            self.active = 'recent'
        elif order == 'overdated':
            qs = CheckList.objects.filter(is_deleted=False, owner=request.user)
            items = []
            for i in qs:
                for j in i.tasks.filter(is_deleted=False):
                    if j.is_overdated():
                        items.append(i)
            self.queryset = items
            self.active = 'overdated'
        else:
            self.queryset = CheckList.objects.filter(is_deleted=False, owner=request.user)  # TODO: order
        return super(HomeIndex, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(HomeIndex, self).get_context_data(**kwargs)
        context['active'] = self.active
        return context


class LateTaskView(ListView):
    model = Task
    template_name = "mylist/tasks.html"
    context_object_name = 'items'

    def get(self, request, *args, **kwargs):
        self.queryset = Task.objects.filter(check_list__owner=request.user, is_deleted=False,
                                            real_due_date__lte=timezone.now())
        return super(LateTaskView, self).get(request)


class PublicView(ListView):
    model = CheckList
    template_name = "mylist/public.html"
    context_object_name = 'items'
    queryset = CheckList.objects.filter(public=True, is_deleted=False)


class DetailView(DetailView):
    model = CheckList
    template_name = "mylist/detail.html"
    slug_field = 'slug'
    pk_url_kwarg = 'id'
    context_object_name = 'checklist'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)

        checklist_id = self.kwargs.get('id')
        context['tasks'] = Task.objects.filter(is_deleted=False,
                                               check_list__id=int(checklist_id),
                                               parent__isnull=True).order_by('due_date')

        return context


class CloneChecklistView(View):

    def post(self, request, *args, **kwargs):
        checklist_id = kwargs.get('id')
        self.old_checklist = CheckList.objects.get(id=int(checklist_id))
        new_checklist_id = request.user.profile.clone_checklist(self.old_checklist)

        return HttpResponse( str(new_checklist_id))


class UpdateTaskView(View):

    def post(self, request, *args, **kwargs):
        task_id = kwargs.get('id')
        self.task = Task.objects.get(id=task_id)
        print task_id

        if request.POST.get('value', 'false') == 'true':
            self.task.is_checked = True

        elif request.POST.get('title', None):
            self.task.title = request.POST.get('title', None)

        else:
            self.task.is_checked = False

        self.task.save()

        return HttpResponse(simplejson.dumps({'result': 'ok'}, ensure_ascii=False))


class AddNewView(FormView):
    model = CheckList
    template_name = "mylist/new.html"
    form_class = ChecklistForm

    def post(self, request, *args, **kwargs):
        title = request.POST.get('title', None)
        start_at = request.POST.get('start_at', timezone.now())
        public = request.POST.get('public', False)
        num_task = request.POST.get('num_task', None)
        tasks = []
        if num_task:
            for i in range(1, int(num_task)+1):
                t = request.POST.get('title%d' % i, '')
                d = request.POST.get('due%d' % i, None)
                if t:
                    tasks.append([t, d])

        if title:
            start_at = datetime.datetime.combine(datetime.datetime.strptime(start_at, "%d/%m/%Y"), datetime.time(0, 0))
            new = self.model.objects.create(title=title, owner=request.user, public=public, start_at=start_at)

            # create tasks
            count = 0
            for t in tasks:
                count += 1
                if t[1]:
                    Task.objects.create(title=t[0], check_list=new, due_date=t[1], order=count)
                else:
                    Task.objects.create(title=t[0], check_list=new, order=count)

            return HttpResponseRedirect(new.get_absolute_url())

        return super(AddNewView, self).post(request)


class UpdateChecklist(FormView):
    template_name = "mylist/update.html"
    form_class = ChecklistForm
    model = CheckList
    initial = {}
    instance = None

    def get_query(self, k):
        checklist_id = k.get('id', None)
        if checklist_id:
            instance = CheckList.objects.get(pk=int(checklist_id))
            return instance
        return None

    def get_context_data(self, **kwargs):
        context = super(UpdateChecklist, self).get_context_data(**kwargs)
        if self.instance:
            context['tasks'] = self.instance.tasks.filter(is_deleted=False)
            context['checklist_id'] = self.instance.id
        return context

    def get(self, request, *args, **kwargs):
        instance = self.get_query(kwargs)
        self.instance = instance
        if instance:
            self.initial['title'] = instance.title
            if instance.start_at is None:
                instance.start_at = timezone.now()
                instance.save()

            self.initial['start_at'] = datetime.datetime.strftime(instance.start_at, "%d/%m/%Y")
            self.initial['public'] = instance.public
        return super(UpdateChecklist, self).get(request)

    def post(self, request, *args, **kwargs):
        title = request.POST.get('title', None)
        start_at = request.POST.get('start_at', timezone.now())
        public = request.POST.get('public', False)
        num_task = request.POST.get('num_task', None)
        tasks = []
        if num_task:
            for i in range(1, int(num_task)):
                t = request.POST.get('title%d' % i, '')
                d = request.POST.get('due%d' % i, None)
                if t:
                    tasks.append([t, d])

        instance = self.get_query(kwargs)
        if title:
            start_at = datetime.datetime.combine(datetime.datetime.strptime(start_at, "%d/%m/%Y"), datetime.time(0, 0))
            instance.title = title
            instance.public = public
            instance.start_at = start_at
            instance.save()

            return HttpResponseRedirect(instance.get_absolute_url())

        return super(UpdateChecklist, self).post(request)


class AddTaskView(View):
    def post(self, request, *args, **kwargs):
        checklist_id = request.POST.get('checklist_id', None)
        if checklist_id:
            checklist = CheckList.objects.get(pk=int(checklist_id))

            num_task = request.POST.get('num_task', None)
            tasks = []
            if num_task:
                for i in range(1, int(num_task)+1):
                    t = request.POST.get('title%d' % i, '')
                    d = request.POST.get('due%d' % i, None)
                    if t:
                        tasks.append([t, d])

            # create tasks
            count = 0
            for t in tasks:
                count += 1
                if t[1]:
                    Task.objects.create(title=t[0], check_list=checklist, due_date=t[1], order=count)
                else:
                    Task.objects.create(title=t[0], check_list=checklist, order=count)

                return HttpResponseRedirect(checklist.get_absolute_url())

        return HttpResponseRedirect('/')

templates/mylist/detail.html
{% extends "base.html" %}
{% load i18n webdesign %}
{% load extra_tags %}
{% block title %}{{ checklist.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="span12">

                {% if request.user == checklist.owner %}
                    <a href="{% url 'mylist:update' checklist.id %}" class="btn btn-success pull-right btn-fork-task"><i
                            class="icon-pencil"></i></a>
                {% elif request.user %}
                    <a href="javascript:clone_checklist({{ checklist.id }});"
                       class="btn btn-warning pull-right btn-fork-task"><i class="icon-ok"></i> Fork this</a>
                {% endif %}
                <a href="javascript:" onclick="window.print();" class="btn btn-success pull-right btn-fork-task"><i
                        class="icon-print"></i></a>

                <h2 class="task-title">{{ checklist.title }}</h2>

                <div class="task-rating pull-left">
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star"></i>
                    <i class="icon-star-half-empty"></i>
                </div>
                <div class="clearfix"></div>
                <hr>
                {% if tasks %}
                    <div class="error" id="msg-error"></div>
                    <ul class="task-list">
                        {% for task in tasks %}

                            <li>
                                <div class="task-contain">
                                    <input type="checkbox" id="task_{{ task.id }}" class="task" value="1" name="t1"
                                           {% if task.is_checked %}checked="true"{% endif %}
                                           data-label="{{ task.title }}"/>

                                    <div>

                                        <div class="pull-left">

                                            {{   task.real_due_date|timeuntil }}

{#                                            {% if task.is_overdated == True %}<p class="remain pull-left over-dated">#}
{#                                                Overdated</p>#}
{#                                                {% elif task.remain_date.days > 0 or task.remain_date.seconds > 3600 %}#}
{#                                                <div class="remain">#}
{#                                                next {{ task.remain_date|remain_date }}</div>{% endif %}#}
                                        </div>

                                        {% if request.user == checklist.owner %}
                                            <div class="pull-left icon-edit task-edit-bt" id="btedit_{{ task.id }}"
                                                 title="Edit" onclick="ShowEditPopup({{ task.id }},'{{ task.title }}')">
                                            </div>
                                        {% endif %}
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                                {% if task.get_child_task.count %}
                                    <ul>
                                        {% for child_task in task.get_child_task %}
                                            <li>
                                                <div class="task-contain">
                                                    <input type="checkbox" id="task_{{ child_task.id }}"
                                                           class="task child_task" value="1" name="tl"
                                                           {% if child_task.is_checked %}checked="true" {% endif %}
                                                           data-label="{{ child_task.title }}"/>

                                                    <div>

                                                        <div class="pull-left">

                                                            {{   task.real_due_date|timeuntil }}
{#                                                            {% if task.is_overdated == True %}#}
{#                                                                <p class="remain pull-left over-dated">Overdated</p>#}
{#                                                                {% elif task.remain_date.days > 0 or task.remain_date.seconds > 3600 %}#}
{#                                                                <div class="remain">#}
{#                                                                next {{ task.remain_date|remain_date }}</div>{% endif %}#}
                                                        </div>

                                                        {% if request.user == checklist.owner %}
                                                            <div class="pull-left  icon-edit task-edit-bt" title="Edit"
                                                                 id="btedit_{{ child_task.id }}" title="Edit"
                                                                 onclick="ShowEditPopup({{ child_task.id }},'{{ child_task.title }}')">
                                                            </div>
                                                        {% endif %}

                                                        <div class="clearfix"></div>
                                                    </div>

                                                </div>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </li>

                        {% endfor %}
                    </ul>
                {% endif %}
                <hr>
                {% if checklist.public %}
                    <div class="task-metadata">
                        <p>by <a
                                href="{% url 'userena_profile_detail' checklist.owner.username %}">{{ checklist.owner.username }}</a>
                        </p>

                        <p>{{ checklist.created_at|timesince }} ago</p>

                        <p>30 people rated</p>

                        <p>200 views</p>

                        <p>3 forks</p>
                    </div>
                {% else %}
                    <div class="task-metadata">
                        <p>by <a
                                href="{% url 'userena_profile_detail' checklist.owner.username %}">{{ checklist.owner.username }}</a>
                        </p>

                        <p>{{ checklist.created_at|timesince }} ago</p>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}prettyCheckable/prettyCheckable.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/print.css" media="print"/>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}prettyCheckable/prettyCheckable.js"></script>
    <script type="text/javascript">
        $(function () {
            var el = $('input.task');
            el.prettyCheckable({
                color: 'green'
            });

            {% if checklist.owner != user %}
                el.attr("disabled", "disabled")
            {% endif %}
        });


        function ShowEditPopup(id, title) {
            var task_title = prompt(title, title);
            if (task_title != null && task_title != "") {
                $.ajax({
                    type: 'POST',
                    url: '/ajax/task/' + id + '/update/',
                    data: 'title=' + task_title,
                    success: function (data) {
                        var obj = $.parseJSON(data);
                        if(obj != '')
                            if(obj.result != undefined && obj.result != '')
                                window.location.reload();
                        else{
                                $("#msg-error").text("Error!")
                            }
                    }
                });
            }else{
                  $("#msg-error").text("Error!")
            }
        }

        $('input.task').on('change', checked);

        function checked() {
            var id = $(this).attr('id').split('_')[1];

            if (id != "") {
                $.ajax({
                    type: 'POST',
                    url: '/ajax/task/' + id + '/update/',
                    data: 'value=' + $(this).is(':checked'),
                    success: function (data) {
                        //console.log("success");
                    }
                });
            }
            console.log($(this).is(':checked'));
        }
    </script>
{% endblock %}

templates/mylist/update.html
{% extends "base.html" %}
{% load i18n webdesign bootstrap %}

{% block title %}Update Checklist{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="span12">
            <h1>{% trans "Update Checklist" %}</h1>
            <hr>
            <form action="" method="post" class="form-horizontal">{% csrf_token %}
                <div class="row">
                    <div class="span12">
                        {{ form|bootstrap }}
                    </div>
                </div>

                <div class="form-actions">
                    <button class="btn btn-primary btn-large">
                        <i class="icon-save"></i> {% trans 'Update Checklist' %}
                    </button>
                </div>
            </form>
            <div class="clearfix"></div>

            <h2 style="margin-top: 30px;">{% trans 'Add tasks' %}</h2>
            <hr>
            <form action="{% url 'mylist:add_tasks' %}" method="post" class="form-horizontal">{% csrf_token %}
                <div ng-app ng-controller="TaskCtrl">
                    <ul class="new-task-list">

                        {% verbatim %}
                            <li ng-repeat="i in tasks" id="task-{{ i }}">
                                <input type="text" name="title{{ i }}" class="span3" placeholder="Task title">
                                <input type="text" name="due{{ i }}" class="span2" placeholder="Complete on (day)">
                            </li>
                        {% endverbatim %}

                    </ul>
                    <div class="clearfix"></div>
                    {% verbatim %}
                        <input type="hidden" name="num_task" value="{{ tasks.length }}">
                        <a ng-click="addLine()" class="btn-naked btn-add-task-line"><i class="icon-plus-sign icon-2x"></i></a>
                    {% endverbatim %}
                </div>
                <div class="form-actions">
                    <button class="btn btn-primary btn-large">
                        <i class="icon-check"></i> {% trans 'Add New Tasks' %}
                    </button>
                    <input type="hidden" name="checklist_id" value="{{ checklist_id }}"/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}datepicker/datepicker.css">
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/angular.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}datepicker/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
    $(function(){
        $('#id_start_at').datepicker({
            format: "dd/mm/yyyy"
        });
    });

    function TaskCtrl($scope) {
        $scope.tasks = [1, 2];

        $scope.addLine = function() {
            var i = $scope.tasks[$scope.tasks.length-1] + 1;
            $scope.tasks.push(i);
        };
    }
    </script>
{% endblock %}