checklist/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('mylist.urls', namespace='mylist')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('userena.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            url(r'', include('django.contrib.staticfiles.urls')),
    )

mylist/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required as LR, permission_required
from mylist.views import HomeIndex, PublicView, DetailView, AddNewView, UpdateTaskView, UpdateChecklist, \
    CloneChecklistView, LateTaskView, AddTaskView

urlpatterns = patterns('mylist.views',
    url('^$', LR(HomeIndex.as_view()), name='index'),
    url('^public/$', PublicView.as_view(), name='public'),
    url('^add/$', LR(AddNewView.as_view()), name='add'),
    url('^ajax/task/(?P<id>\d+)/update/$', permission_required('tasks.can_edit')(UpdateTaskView.as_view()), name='update_task'),

    url('^ajax/checklist/(?P<id>\d+)/clone/$', LR(CloneChecklistView.as_view()), name='clone_checklist'),
    url('^checklist/(?P<slug>[-_\w]+)/(?P<id>\d+)/$', DetailView.as_view(), name='detail'),
    url('^checklist/(?P<id>\d+)/update/$', UpdateChecklist.as_view(), name='update'),
    url('^tasks/late/$', LR(LateTaskView.as_view()), name='late_tasks'),
    url('^tasks/add/$', LR(AddTaskView.as_view()), name='add_tasks'),
)

userena/urls.py
from django.conf.urls import *
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from userena import views as userena_views
from userena import settings as userena_settings

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       {'template_name': 'userena/password_reset_form.html',
        'email_template_name': 'userena/emails/password_reset_message.txt'},
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html'},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
       auth_views.password_reset_confirm,
       {'template_name': 'userena/password_reset_confirm_form.html'},
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'}),

    # Signup
    url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

templates/base.html
{% load i18n webdesign %}
<!DOCTYPE html>
<html lang="vi" class="no-js">
<head>
{#    <meta id="vp" name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">#}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Checklist Simply{% endblock %}</title>
    <meta name="description" content="{% block desc %}{% endblock %}">
    <meta name="viewport" content="width=device-width">

    <link rel="ame="viewport" content="target-densitydpi=device-dpi, width=device-width, user-scalable=no, maximum-scale=1, minimum-scale=1" />
    <apple-touch-icon" href="{{ STATIC_URL }}favicon.png">
    <link rel="shortcut icon" type="image/x-icon" href="{{ STATIC_URL }}favicon.ico">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <script src="{{ STATIC_URL }}js/modernizr-2.6.2.min.js"></script>

    {% block extra_css %}{% endblock %}
{##}
{#<script type="text/javascript">#}
{#		var vp = document.getElementById("vp");#}
{#        vp.setAttribute('name', 'viewport');#}
{#        vp.setAttribute('content', 'initial-scale=' + (1 / window.devicePixelRatio) + ',user-scalable=no');#}
{#</script>#}
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/"><span></span></a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="{% url 'mylist:index' %}">{% trans 'My Checklist' %}</a></li>
                    <li><a href="{% url 'mylist:public' %}">{% trans 'Public' %}</a></li>
                </ul>

                <form class="navbar-search" action="">
                    <div class="input-append">
                        <input type="text" class="span2 search-query" placeholder="Search" maxlength="100">
                    </div>
                </form>

                {% if request.user.is_authenticated %}
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon-user"></i> {{ request.user.username }} <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'userena_profile_detail' request.user.username %}">{% trans 'Profile' %}</a></li>
                                {% if request.user.is_staff %}
                                    <li><a href="{% url 'admin:index' %}">{% trans 'Admin' %}</a></li>
                                {% endif %}
                                <li class="divider"></li>
                                <li><a href="{% url 'userena_signout' %}">{% trans 'Logout' %}</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <ul class="nav pull-right">
                        <li><a href="{% url 'userena_signin' %}">{% trans "Login" %}</a></li>
                        <li><a href="{% url 'userena_signup' %}">{% trans "Create New Account" %}</a></li>
                    </ul>
                {% endif %}
            </div>

            <a href="{% url 'mylist:add' %}" class="btn btn-danger pull-right btn-add-new" style="margin-right: 10px;">
                <i class="icon-plus-sign"></i> {% trans 'Add New' %}
            </a>

        </div>
    </div>
</div>

{% block content %}{% endblock %}

<script src="{{ STATIC_URL }}js/jquery-2.0.0.min.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.js"></script>
<script src="{{ STATIC_URL }}js/plugins.js"></script>
<script src="{{ STATIC_URL }}js/main.js"></script>
{% block extra_js %}{% endblock %}
{#<script>#}
{#    var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];#}
{#    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];#}
{#    g.src='//www.google-analytics.com/ga.js';#}
{#    s.parentNode.insertBefore(g,s)}(document,'script'));#}
{#</script>#}
</body>
</html>